# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 443)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 9, 611, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.value1 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.value1.setObjectName("value1")
        self.verticalLayout.addWidget(self.value1)
        self.copyBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.copyBtn.setObjectName("copyBtn")
        self.verticalLayout.addWidget(self.copyBtn)
        self.pasteBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pasteBtn.setObjectName("pasteBtn")
        self.verticalLayout.addWidget(self.pasteBtn)
        self.value2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.value2.setReadOnly(True)
        self.value2.setObjectName("value2")
        self.verticalLayout.addWidget(self.value2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.copyBtn.setText(_translate("Dialog", "Kopiuj"))
        self.pasteBtn.setText(_translate("Dialog", "Wklej"))
